#!/usr/bin/env python3
"""Derive the arrival bands for each rung and generate `src/ladder_reference.py`.

Costs nothing. `scripts/capture_model_reference.py` bought the renderings; this is local
signal processing over files already on disk, and it can be re-run every time the measurement
changes. Same contract `build_model_reference.py` holds: **re-deriving a reference must never
mean re-spending.**

    docker compose run --rm app python scripts/build_ladder_reference.py

## What an arrival band is, and why it needs the spread

`app._pitch_findings` already computes exactly these scalars for the model voices and then
takes their MEAN as the target, discarding how far the voices sat from each other. A mean
alone answers "what is typical" and cannot answer "am I inside the range native talkers
occupy" — which is the question `#39`'s measured resolution turns on. This keeps the spread
the existing code throws away.

## Four decisions worth knowing before reading a number out of the output

**1. The sound rung is not here.** `model_reference.sd50` already carries a between-voice
formant spread per vowel, generated by `build_model_reference.py`. Publishing a second sound
band would be two sources of truth for one claim, and they would drift.

**2. Every scalar is pooled across all sixteen voices, not split by sex.** `model_reference`
splits because formants scale with vocal tract length. Nothing here does: a semitone range is
a log ratio, a terminal slope is a difference of log ratios, nPVI is a ratio by construction,
and a relative word duration is divided by the voice's own mean. None of them carries an F0
register or a tract length, so splitting would halve the sample for no gain.

**3. Word duration is relative, never milliseconds.** Sixteen voices read at sixteen rates and
the user reads at a seventeenth. A band in milliseconds would mostly measure speaking rate; a
word divided by its own voice's mean word duration measures reduction, which is the thing the
word rung is actually about. Same normalising move `vowel_measure.Normaliser` makes for
formants, one level up.

**4. A unit is published only when enough voices produced it cleanly**, and one that does not
clear the bar is omitted rather than emitted from a handful of talkers — the same rule
`build_model_reference.py` follows, and the same reason: a thin reference has to look thin.
"""

from __future__ import annotations

import argparse
import logging
import statistics
import sys
import textwrap
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import accent_resynth  # noqa: E402
import db  # noqa: E402
import ladder  # noqa: E402
import native_model  # noqa: E402
import progress_view  # noqa: E402
import shadowing  # noqa: E402
import speech_analyzer  # noqa: E402
import utils  # noqa: E402

OUT = ROOT / "src" / "ladder_reference.py"

# Below this many voices a spread is not a distribution. Matches `native_model`'s own floor
# for a reference set, and for the same stated reason.
MIN_VOICES = native_model.MIN_VOICES_PER_SET

# What each rung is judged on comes from `ladder.METRICS` rather than a second list here: a
# metric added to the surface and forgotten in the builder would silently ship without a band.


@dataclass
class VoiceScalars:
    """One voice's reading, reduced to the scalars each rung is judged on."""

    voice: str
    words: dict[int, dict[str, float]] = field(default_factory=dict)
    sentences: dict[int, dict[str, float]] = field(default_factory=dict)
    paragraph: dict[str, float] = field(default_factory=dict)


def measure(rendering: native_model.Rendering, text: str) -> VoiceScalars | None:
    """Reduce one rendering to per-rung scalars. None when it cannot be measured at all.

    Every number comes out of `ladder.scalars`, the same function the practice surface uses on
    the speaker. That is deliberate: a band and the comparison against it must not be able to
    drift into measuring different quantities.
    """
    audio = rendering.audio()
    if audio is None:
        return None
    words = rendering.words()
    track = accent_resynth.pitch_track(audio)
    divisor = ladder.mean_word_seconds(words)
    found = VoiceScalars(rendering.voice)

    for span in ladder.word_spans(words):
        measured = ladder.scalars(span, words, track, divisor=divisor)
        if measured:
            found.words[span.word_indices[0]] = measured

    for index, span in enumerate(ladder.sentence_spans(words, text)):
        measured = ladder.scalars(span, words, track, divisor=divisor)
        if measured:
            found.sentences[index] = measured

    whole = ladder.paragraph_span(words, text)
    if whole is not None:
        overall, _, _ = speech_analyzer.normalise(
            rendering.payloads, rendering.reference_text, native_model.CAPTURE_MODE
        )
        prosody = overall.get("prosody")
        found.paragraph = ladder.scalars(
            whole,
            words,
            track,
            divisor=divisor,
            prosody=float(prosody) if isinstance(prosody, int | float) else None,
        )

    return found


def band(metric: str, values: Sequence[float]) -> ladder.Band | None:
    """Mean and between-voice SD, or None when too few voices produced the metric."""
    if len(values) < MIN_VOICES:
        return None
    return ladder.Band(
        metric=metric,
        mean=statistics.fmean(values),
        sd=statistics.stdev(values),
        voices=len(values),
    )


def collect(
    per_voice: Sequence[Mapping[int, Mapping[str, float]]], metrics: Sequence[str]
) -> dict[int, dict[str, ladder.Band]]:
    """Bands per unit index, across voices. Units with no publishable band are dropped."""
    indices = sorted({index for voice in per_voice for index in voice})
    built: dict[int, dict[str, ladder.Band]] = {}
    for index in indices:
        bands: dict[str, ladder.Band] = {}
        for metric in metrics:
            values = [
                float(voice[index][metric])
                for voice in per_voice
                if index in voice and metric in voice[index]
            ]
            made = band(metric, values)
            if made is not None:
                bands[metric] = made
        if bands:
            built[index] = bands
    return built


def _band_src(value: ladder.Band) -> str:
    return (
        f"Band(metric={value.metric!r}, mean={value.mean:.4f}, "
        f"sd={value.sd:.4f}, voices={value.voices})"
    )


def _unit_block(name: str, units: Mapping[int, Mapping[str, ladder.Band]]) -> str:
    if not units:
        return f"{name}: Mapping[int, Mapping[str, Band]] = {{}}\n"
    lines = [f"{name}: Mapping[int, Mapping[str, Band]] = {{"]
    for index in sorted(units):
        lines.append(f"    {index}: {{")
        for metric in sorted(units[index]):
            lines.append(f"        {metric!r}: {_band_src(units[index][metric])},")
        lines.append("    },")
    lines.append("}\n")
    return "\n".join(lines)


def render_module(
    words: Mapping[int, Mapping[str, ladder.Band]],
    sentences: Mapping[int, Mapping[str, ladder.Band]],
    paragraph: Mapping[str, ladder.Band],
    voices: Sequence[str],
    sentence_labels: Sequence[str],
) -> str:
    """The generated module's source. Every number in it came from a measurement above."""
    listed = "\n".join(textwrap.wrap(", ".join(sorted(voices)), width=94))
    labels = "\n".join(f"    {index}: {label!r}," for index, label in enumerate(sentence_labels))
    paragraph_src = "\n".join(
        f"    {metric!r}: {_band_src(paragraph[metric])}," for metric in sorted(paragraph)
    )
    return f'''"""Arrival bands per rung, measured by this project through its own pipeline.

**GENERATED FILE. Do not hand-edit.** Every number below is produced by
`scripts/build_ladder_reference.py` from renderings captured by
`scripts/capture_model_reference.py`; re-run those instead. Same rule as
`model_reference.py`: no reference number in this project is ever typed from memory.

Derived {datetime.now(UTC).strftime("%Y-%m-%d")} from benchmark passage
v{progress_view.BENCHMARK_VERSION}, read by {len(voices)} en-US neural voices:
{listed}

## What this answers

"Am I inside the range native talkers occupy for this unit" — the arrival half of `#39`'s
measured resolution. The other half, whether the change cleared the speaker's own
session-to-session variation, is `vowel_measure.NoiseFloor` and is not here.

## What is deliberately absent

**The sound rung.** `model_reference.sd50` already carries a between-voice formant spread per
vowel. A second sound band would be two sources of truth for one claim.

**Milliseconds.** Word bands are duration relative to the reading's own mean word, so they
measure reduction rather than speaking rate.

**Anything split by sex.** Every scalar here is a ratio or a log ratio and carries no vocal
tract length, unlike the formants `model_reference` has to split.

Keyed by index into the benchmark passage — word index for `WORD`, sentence index for
`SENTENCE`. A changed passage invalidates those keys, which is what `BENCHMARK_VERSION`
records.
"""

from __future__ import annotations

from collections.abc import Mapping

from ladder import Band

BENCHMARK_VERSION = {progress_view.BENCHMARK_VERSION}
VOICES = {len(voices)}

# The sentence each index refers to, so a band can be read without re-splitting the passage.
SENTENCE_TEXT: Mapping[int, str] = {{
{labels}
}}

{_unit_block("WORD", words)}

{_unit_block("SENTENCE", sentences)}

PARAGRAPH: Mapping[str, Band] = {{
{paragraph_src}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", action="store_true", help="Write to stdout, not to the file.")
    args = parser.parse_args()
    utils.configure_logging(logging.INFO)

    conn = db.connect()
    text = progress_view.BENCHMARK_PASSAGE
    stored = native_model.renderings_for(conn, text)
    if not stored:
        print("[ladder] no captured renderings. Run scripts/capture_model_reference.py first.")
        return 1

    print(f"[ladder] measuring {len(stored)} rendering(s) …")
    measured: list[VoiceScalars] = []
    for rendering in sorted(stored, key=lambda r: r.voice):
        found = measure(rendering, text)
        if found is None:
            print(f"[ladder]   {rendering.voice}: audio missing, skipped")
            continue
        print(
            f"[ladder]   {rendering.voice}: {len(found.words)} words, "
            f"{len(found.sentences)} sentences, {len(found.paragraph)} paragraph metrics"
        )
        measured.append(found)

    if len(measured) < MIN_VOICES:
        print(
            f"[ladder] only {len(measured)} measurable rendering(s), and a between-voice band "
            f"needs {MIN_VOICES}. Refusing rather than publishing a spread computed from a "
            f"handful of talkers."
        )
        return 1

    words = collect([v.words for v in measured], ladder.METRICS[ladder.Rung.WORD])
    sentences = collect([v.sentences for v in measured], ladder.METRICS[ladder.Rung.SENTENCE])
    paragraph: dict[str, ladder.Band] = {}
    for metric in ladder.METRICS[ladder.Rung.PARAGRAPH]:
        values = [v.paragraph[metric] for v in measured if metric in v.paragraph]
        made = band(metric, values)
        if made is not None:
            paragraph[metric] = made

    print(
        f"[ladder] published: {len(words)} word band(s), {len(sentences)} sentence band(s), "
        f"{len(paragraph)} paragraph metric(s)"
    )
    for metric in sorted(paragraph):
        value = paragraph[metric]
        print(f"[ladder]   paragraph {metric}: {value.mean:.2f} ± {value.sd:.2f} SD")

    source = render_module(
        words,
        sentences,
        paragraph,
        [v.voice for v in measured],
        shadowing.phrases(text),
    )
    if args.print:
        print(source)
        return 0
    OUT.write_text(source, encoding="utf-8")
    print(f"[ladder] wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
